"""initial schema

Revision ID: 7bf3e71785b6
Revises: 
Create Date: 2026-07-15 19:27:23.616003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf3e71785b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('opening', sa.String(length=255), nullable=False),
    sa.Column('eco', sa.String(length=8), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('opening_book_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eco', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pgn_moves', sa.Text(), nullable=False),
    sa.Column('san_moves_json', sa.Text(), nullable=False),
    sa.Column('ply_count', sa.Integer(), nullable=False),
    sa.Column('final_fen', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eco', 'name', name='uq_opening_book_eco_name')
    )
    op.create_index(op.f('ix_opening_book_entries_eco'), 'opening_book_entries', ['eco'], unique=False)
    op.create_index(op.f('ix_opening_book_entries_final_fen'), 'opening_book_entries', ['final_fen'], unique=False)
    op.create_index(op.f('ix_opening_book_entries_name'), 'opening_book_entries', ['name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fide_id', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'fide_id', name='uq_player_name_fide')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('white_player_id', sa.Integer(), nullable=False),
    sa.Column('black_player_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('round', sa.String(length=32), nullable=True),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('result', sa.Enum('WHITE_WIN', 'BLACK_WIN', 'DRAW', 'UNKNOWN', name='gameresult'), nullable=False),
    sa.Column('eco_code', sa.String(length=8), nullable=True),
    sa.Column('opening_name', sa.String(length=255), nullable=True),
    sa.Column('opening_variation', sa.String(length=255), nullable=True),
    sa.Column('tracked_player_color', sa.Enum('WHITE', 'BLACK', name='color'), nullable=True),
    sa.Column('pgn_raw', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('UPLOAD', 'SEED', name='gamesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['black_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_eco_code'), 'games', ['eco_code'], unique=False)
    op.create_index(op.f('ix_games_opening_name'), 'games', ['opening_name'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('color', sa.Enum('WHITE', 'BLACK', name='color'), nullable=False),
    sa.Column('san', sa.String(length=16), nullable=False),
    sa.Column('uci', sa.String(length=8), nullable=False),
    sa.Column('fen_before', sa.String(length=100), nullable=False),
    sa.Column('fen_after', sa.String(length=100), nullable=False),
    sa.Column('is_book_move', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'ply', name='uq_move_game_ply')
    )
    op.create_index(op.f('ix_moves_game_id'), 'moves', ['game_id'], unique=False)
    op.create_table('theory_exits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('exit_ply', sa.Integer(), nullable=False),
    sa.Column('exit_move_number', sa.Integer(), nullable=False),
    sa.Column('color_to_move', sa.Enum('WHITE', 'BLACK', name='color'), nullable=False),
    sa.Column('eco_code', sa.String(length=8), nullable=True),
    sa.Column('opening_name', sa.String(length=255), nullable=True),
    sa.Column('opening_variation', sa.String(length=255), nullable=True),
    sa.Column('expected_move_san', sa.String(length=16), nullable=True),
    sa.Column('played_move_san', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.Column('mistake_type', sa.Enum('EARLY_QUEEN_DEVELOPMENT', 'DELAYED_CASTLING', 'PREMATURE_PAWN_PUSH', 'IGNORED_CENTER_CONTROL', 'LOST_TEMPO', 'REPEATED_PIECE_MOVES', 'THEORY_DEVIATION', name='mistaketype'), nullable=False),
    sa.Column('color', sa.Enum('WHITE', 'BLACK', name='color'), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('ply', sa.Integer(), nullable=False),
    sa.Column('san', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eval_loss', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mistakes_game_id'), 'mistakes', ['game_id'], unique=False)
    op.create_index(op.f('ix_mistakes_mistake_type'), 'mistakes', ['mistake_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mistakes_mistake_type'), table_name='mistakes')
    op.drop_index(op.f('ix_mistakes_game_id'), table_name='mistakes')
    op.drop_table('mistakes')
    op.drop_table('theory_exits')
    op.drop_index(op.f('ix_moves_game_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_games_opening_name'), table_name='games')
    op.drop_index(op.f('ix_games_eco_code'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_opening_book_entries_name'), table_name='opening_book_entries')
    op.drop_index(op.f('ix_opening_book_entries_final_fen'), table_name='opening_book_entries')
    op.drop_index(op.f('ix_opening_book_entries_eco'), table_name='opening_book_entries')
    op.drop_table('opening_book_entries')
    op.drop_table('kb_sources')
    # ### end Alembic commands ###
